export default {
  standardItems: [
    {
      contentType: 'recipe',
      contentTypeFormatted: 'Recipe',
      commentCount: 23,
      ctaText: '',
      ctaUrl: '',
      href: '/recipes/8125',
      imageAlt: 'Chocolate Crinkle Cookies',
      imageUrl: 'https://res.cloudinary.com/hksqkdlah/image/upload/ar_1:1,c_fill,dpr_2.0,f_auto,fl_lossy.progressive.strip_profile,g_faces:auto,q_auto:low,w_344/22391_sfs-chocolate-crinkle-cookies-35',
      objectId: 'recipe_8125',
      siteKey: 'atk',
      siteKeyFavorites: 'atk',
      title: 'Chocolate Crinkle Cookies',
    },
    {
      contentType: 'recipe',
      contentTypeFormatted: 'Recipe',
      commentCount: 23,
      ctaText: '',
      ctaUrl: '',
      href: '/recipes/8125',
      imageAlt: 'Chocolate Crinkle Cookies',
      imageUrl: 'https://res.cloudinary.com/hksqkdlah/image/upload/ar_1:1,c_fill,dpr_2.0,f_auto,fl_lossy.progressive.strip_profile,g_faces:auto,q_auto:low,w_344/22391_sfs-chocolate-crinkle-cookies-35',
      objectId: 'recipe_8125',
      siteKey: 'atk',
      siteKeyFavorites: 'atk',
      title: 'Chocolate Crinkle Cookies',
    },
    {
      contentType: 'recipe',
      contentTypeFormatted: 'Recipe',
      commentCount: 23,
      ctaText: '',
      ctaUrl: '',
      href: '/recipes/8125',
      imageAlt: 'Chocolate Crinkle Cookies',
      imageUrl: 'https://res.cloudinary.com/hksqkdlah/image/upload/ar_1:1,c_fill,dpr_2.0,f_auto,fl_lossy.progressive.strip_profile,g_faces:auto,q_auto:low,w_344/22391_sfs-chocolate-crinkle-cookies-35',
      objectId: 'recipe_8125',
      siteKey: 'atk',
      siteKeyFavorites: 'atk',
      title: 'Chocolate Crinkle Cookies',
    },
    {
      contentType: 'recipe',
      contentTypeFormatted: 'Recipe',
      commentCount: 23,
      ctaText: '',
      ctaUrl: '',
      href: '/recipes/8125',
      imageAlt: 'Chocolate Crinkle Cookies',
      imageUrl: 'https://res.cloudinary.com/hksqkdlah/image/upload/ar_1:1,c_fill,dpr_2.0,f_auto,fl_lossy.progressive.strip_profile,g_faces:auto,q_auto:low,w_344/22391_sfs-chocolate-crinkle-cookies-35',
      objectId: 'recipe_8125',
      siteKey: 'atk',
      siteKeyFavorites: 'atk',
      title: 'Chocolate Crinkle Cookies',
    },
    {
      contentType: 'recipe',
      contentTypeFormatted: 'Recipe',
      commentCount: 23,
      ctaText: '',
      ctaUrl: '',
      href: '/recipes/8125',
      imageAlt: 'Chocolate Crinkle Cookies',
      imageUrl: 'https://res.cloudinary.com/hksqkdlah/image/upload/ar_1:1,c_fill,dpr_2.0,f_auto,fl_lossy.progressive.strip_profile,g_faces:auto,q_auto:low,w_344/22391_sfs-chocolate-crinkle-cookies-35',
      objectId: 'recipe_8125',
      siteKey: 'atk',
      siteKeyFavorites: 'atk',
      title: 'Chocolate Crinkle Cookies',
    },
  ],
  featureItems: [
    {
      attributions: 'Episode • Cook’s Country',
      contentType: 'episode',
      href: '/episodes/1234',
      imageAlt: ' ',
      imageUrl: 'https://res.cloudinary.com/hksqkdlah/image/upload/v1591972592/mise-play/feature-card-tacos.jpg',
      objectId: 'episode_1234',
      siteKey: 'cco',
      siteKeyFavorites: 'cco',
      title: 'Tacos Two Ways',
      stickers: [{ type: 'priority', text: 'new' }, { type: 'editorial', text: '28:03' }],
    },
    {
      attributions: 'Popular • America’s Test Kitchen',
      contentType: 'review',
      ctaText: 'Buy the Winner',
      ctaUrl: 'http://google.com',
      href: '/episodes/1234',
      imageAlt: ' ',
      imageUrl: 'https://res.cloudinary.com/hksqkdlah/image/upload/v1591972592/mise-play/feature-card-tacos.jpg',
      objectId: 'episode_1234',
      siteKey: 'cco',
      siteKeyFavorites: 'cco',
      title: 'Tacos Two Ways',
      stickers: [{ type: 'editorial', text: 'Popular' }],
    },
    {
      attributions: 'Episode • Cook’s Country',
      contentType: 'episode',
      href: '/episodes/1234',
      imageAlt: ' ',
      imageUrl: 'https://res.cloudinary.com/hksqkdlah/image/upload/v1591972592/mise-play/feature-card-tacos.jpg',
      objectId: 'episode_1234',
      siteKey: 'cco',
      siteKeyFavorites: 'cco',
      title: 'Tacos Two Ways',
      stickers: [{ type: 'priority', text: 'new' }, { type: 'editorial', text: '28:03' }],
    },
    {
      attributions: 'Popular • America’s Test Kitchen',
      contentType: 'review',
      ctaText: 'Buy the Winner',
      ctaUrl: 'http://google.com',
      href: '/episodes/1234',
      imageAlt: ' ',
      imageUrl: 'https://res.cloudinary.com/hksqkdlah/image/upload/v1591972592/mise-play/feature-card-tacos.jpg',
      objectId: 'episode_1234',
      siteKey: 'cco',
      siteKeyFavorites: 'cco',
      title: 'Tacos Two Ways',
      stickers: [{ type: 'editorial', text: 'Popular' }],
    },
    {
      attributions: 'Episode • Cook’s Country',
      contentType: 'episode',
      href: '/episodes/1234',
      imageAlt: ' ',
      imageUrl: 'https://res.cloudinary.com/hksqkdlah/image/upload/v1591972592/mise-play/feature-card-tacos.jpg',
      objectId: 'episode_1234',
      siteKey: 'cco',
      siteKeyFavorites: 'cco',
      title: 'Tacos Two Ways',
      stickers: [{ type: 'priority', text: 'new' }, { type: 'editorial', text: '28:03' }],
    },
  ],
};
